language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4

install:
    - pip install numpy
    - pip install coveralls
    - pip install coverage
    - python setup.py install

script:
    - coverage run -m dicom.test.run_tests

after_success:
    - coveralls
