language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4

env:
    - DEPS=true
    - DEPS=false

install:
    - if [[ $DEPS == true ]]; then pip install numpy; fi
    - pip install coveralls
    - pip install coverage
    - python setup.py install

script:
    - cp .coveragerc build/lib/
    - cd build/lib
    - coverage run -m dicom.test.run_tests

after_success:
    - coveralls
