language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4

install:
    - cd $TRAVIS_BUILD_DIR/source
    - pip install numpy
    - pip install coveralls
    - python setup.py install
    - cd $TRAVIS_BUILD_DIR 

script:
    - coverage run -m dicom.test.run_tests

after_success:
    - coveralls
